// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlUXw652ZHMiSBSPx1NPrrWMSybBlgts',
    appId: '1:214571930608:web:dc75622bd44f21cb344335',
    messagingSenderId: '214571930608',
    projectId: 'sentinal-56dc9',
    authDomain: 'sentinal-56dc9.firebaseapp.com',
    storageBucket: 'sentinal-56dc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0sBF0_JTVxb7KNVDc7NloJHrsyQ5Dso',
    appId: '1:214571930608:android:1ce15b37c4a2d3e7344335',
    messagingSenderId: '214571930608',
    projectId: 'sentinal-56dc9',
    storageBucket: 'sentinal-56dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHJHI1B6k6bzJCe7hN_ZthmBK6UEzHsc',
    appId: '1:214571930608:ios:cf2c82699c64c643344335',
    messagingSenderId: '214571930608',
    projectId: 'sentinal-56dc9',
    storageBucket: 'sentinal-56dc9.firebasestorage.app',
    iosBundleId: 'com.example.sentinal',
  );

}